version: '3.6'

services:

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: apsu777/flask_web:latest
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_CODE=myprecious
    depends_on:
      - db
    networks:
      - app
    secrets:
      - secret_code

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    image: apsu777/flask_db:latest
    volumes:
      - data-volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: apsu777/flask_nginx:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  data-volume:
    driver: local

secrets:
    secret_code:
          external: true

