version: '3.6'

services:
  jenkins:
    image: jenkins
    entrypoint: ["/sbin/tini" , "--", "/usr/local/bin/jenkins-init.sh"]
    networks:
      - app
    volumes:
      - "jenkins_vol:/var/jenkins_home"              # persistent
      - "/var/run/docker.sock:/var/run/docker.sock"  # docker from jenkins
        #      - "/usr/bin/docker:/bin/docker"                # docker from jenkins
    ports:
      - 8880:8080
      - 50000:50000
    configs:
      - source: jenkins-init.sh
        target: /user/local/bin/jenkins-init.sh
        mode: 0777

configs:
 jenkins-init.sh:
   file: ./services/jenkins/init.sh

networks:
  app:
    driver: overlay

volumes:
  jenkins_vol: 
    driver: local
