version: '3.6'

services:

  traefik:
    image: traefik
    env_file:
      - .env
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=${domain_name} \
      --docker.watch \
      --logLevel=DEBUG
      --web
    networks:
      - app
    ports:
      - "8090:80"
      - "8091:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]

  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "portainerdata:/data"
    env_file:
      - .env
    networks:
      - app
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=traefik_app"
        - "traefik.frontend.rule=Host:portainer.${domain_name}"

networks:
  app:
    driver: overlay

