pipeline{
    agent: any
    options {
        buildDiscarder(LogRotator(numToKeepStr: '5'))
    }

    stages {
        stage('docker-hello-world-pipeline'){
            steps{
                sh 'echo hello_world'
            }
        }
    }
    
    post {
        always{
            sh 'echo this always run'
        }
    }

}
