#!/bin/env groovy 
// go , sq  , artifactory

pipeline {

  agent any
  
  triggers {
    pollSCM('* * * * *')
  }

  options {
      // timeout(time: 1, unit: 'HOURS')
      timeout(time: 15, unit: 'MINUTES')
      buildDiscarder(logRotator(numToKeepStr: '5'))

  }

  stages {
     stage ('stage1') {echo "hello"}
 
  }


}
